# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Data at the Point of Care
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dpc.cms.gov" # the base hostname & protocol for your site, e.g. http://example.com
cssurl: /assets/css/static-main.css
logourl: /assets/images/top-nav-heart.svg

global_nav:
  - title: Home
    id: home
  - title: Documentation
    id: docs
  - title: Frequently Asked Questions
    id: faq

footer_nav:
  - title: Documentation
    id: docs
  - title: Frequently asked questions
    id: faq
  - title: Terms of Service
    id: tos

guide_nav:
  - title: Authorization
    id: authorization
    subnav:
      - title: Step One&#x3a; Request Access
        id: step-one-request-access
      - title: Step Two&#x3a; Client Tokens
        id: step-two-client-tokens
      - title: Step Three&#x3a; Public Keys
        id: step-three-public-keys
      - title: Step Four&#x3a; JSON Web Tokens
        id: step-four-json-web-tokens
      - title: Step Five&#x3a; Access/Bearer Token
        id: step-five-accessbearer-token
  - title: Attestation & Attribution
    id: attestation--attribution
    subnav:
      - title: Load Sample Data
        id: load-sample-data
      - title: Practitioners
        id: practitioners
      - title: Patients
        id: patients
      - title: Attestation
        id: attestation
      - title: Groups (Attribution)
        id: groups-attribution
  - title: Export Data
    id: export-data
    subnav:
      - title: Initiate an Export Job
        id: initiate-an-export-job
      - title: Specify Resources
        id: specify-which-resources-to-download
      - title: Check Status of Export Job
        id: check-status-of-the-export-job
      - title: Retrieve NDJSON Output
        id: retrieve-the-ndjson-output-files
  - title: Postman Collection
    id: postman-collection
    subnav:
      - title: Patient/$everything
        id: patienteverything

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  load_paths:
    - _sass
    - node_modules
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
