version: '3'

services:
  static_site:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.static_site
    volumes:
      - ./_site:/dpc-site-static/_site
      - ./.jekyll-cache:/dpc-site-static/.jekyll-cache
