FROM jekyll/builder:4.2.0

ENV BUNDLE_PATH=$GEM_HOME
WORKDIR /dpc-site-static

# Install dependencies so they can be cached
# separately from other application files
COPY ./package.json package.json
COPY ./package-lock.json package-lock.json
RUN npm install

COPY ./Gemfile Gemfile
COPY ./Gemfile.lock Gemfile.lock
RUN bundle install

COPY . .
ENTRYPOINT ["bundle", "exec", "jekyll", "build", "--config", "_config.yml,_version_config.yml"]
