name: "Broken Link Check"

on:
  push:
  schedule:
    - cron: 0 0 * * * # run daily at midnight

jobs:
  check:
    name: "Check for broken links"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Check for broken links"
        uses: lycheeverse/lychee-action@v1
        with:
          fail: true
          jobSummary: true
          args: --accept '200..=299, 401, 405' .
