on:
  repository_dispatch:
  workflow_dispatch:
  push:
  schedule:
    - cron: 0 0 * * * # run daily at midnight

name: Broken Link Check
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Broken Link Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://dpc.cms.gov/
