name: "Broken Link Check"

on:
  workflow_dispatch:
    inputs:
      repo_ref:
        default: "hey"
        description: "hey"

jobs:
  check:
    name: "Check for broken links"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
