name: "Broken Link Check"

on:
  schedule:
    - cron: 0 0 * * 0 # run every Sunday at midnight
  workflow_dispatch:

jobs:
  check:
    name: "Check for broken links"
    runs-on: codebuild-dpc-static-site-${{github.run_id}}-${{github.run_attempt}}
    steps:
      - name: "Send Slack alert"
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          # Sends to dpc-deploys
          payload: |
            channel: "CUY7H43DY"
            text:  "TESTING IGNORE"
            attachments:
              - color: danger
                fields:
                  - title: Broken link(s) found
                    value: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
