name: "Broken Link Check"

on:
  push:
  schedule:
    - cron: 0 0 * * * # run daily at midnight

jobs:
  check:
    name: "Check for broken links"
    runs-on: ubuntu-latest
    steps:
      - name: "Check for broken links"
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --accept '200..=299, 401' --exclude .*\.ndjson file://* -- ./common # ignore Unauthorized
          fail: true
          jobSummary: true
