on:
  schedule:
    - cron: 0 0 * * * # run daily
  repository_dispatch: # run manually
    types: [check-link]
  push: # run on push

name: Broken Link Check
jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Check for broken links
        id: link-report
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://dpc.cms.gov
          pages_path: ./_site/
