name: Check 508 Compliance

on:
  schedule:
    - cron: 17 8 * * 1
  workflow_dispatch:
    inputs:
      target_host:
        description: Check where?
        required: true
        default: 'https://stage.dpc.cms.gov'
        type: choice
        options:
          - 'https://stage.dpc.cms.gov'
          - 'https://dpc.cms.gov'

jobs:
  compliance_check:
    name: Compliance Check
    runs-on: self-hosted
    steps:
      - name: Set Target Base
        id: target-base
        run: |
          echo "${{ inputs.target_host || 'https://stage.dpc.cms.gov' }}=TARGET_BASE_URL" >> "$GITHUB_OUTPUT"
      - name: Run Axe Check
        env:
          TARGET_BASE_URL: ${{ steps.target-base.outputs.TARGET_BASE_URL }}
        run: |
          echo $TARGET_BASE_URL
