name: Check 508 Compliance

on:
  push:
    paths:
      - .github/workflows/check_508_compliance.yml

jobs:
  compliance_check:
    name: Compliance Check
    runs-on: ubuntu-latest
    steps:
      - name: Run Axe Check
        env:
          TARGET_BASE_URL: 'https://stage.dpc.cms.gov'
        run: |
          TARGETS_TO_SCAN="${TARGET_TEST_ENV}"
          TARGETS_TO_SCAN="${TARGETS_TO_SCAN} ${TARGET_TEST_ENV}/faq.html"
          TARGETS_TO_SCAN="${TARGETS_TO_SCAN} ${TARGET_TEST_ENV}/data.html"
          TARGETS_TO_SCAN="${TARGETS_TO_SCAN} ${TARGET_TEST_ENV}/pilot.html"
          TARGETS_TO_SCAN="${TARGETS_TO_SCAN} ${TARGET_TEST_ENV}/docsV1.html"
          TARGETS_TO_SCAN="${TARGETS_TO_SCAN} ${TARGET_TEST_ENV}/docsV2.html" 
          TARGETS_TO_SCAN="${TARGETS_TO_SCAN} ${TARGET_TEST_ENV}/updates.html"
          RESULTS=`docker run --init --rm --cap-add=SYS_ADMIN orenfromberg/axe-puppeteer-ci:1.0.0@sha256:f83527a3ae8ab74088c001abfe44836946ba73f0afbbf460447f8a0c40281e70 ${TARGETS_TO_SCAN}`
          echo $RESULTS
          
