name: "DPC Static Site CI Workflow"

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy or just tag?'
        type: boolean
        default: true
        required: true
        
jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - name: Run if true
        if:  ${{ inputs.deploy }}
        run: |
          echo 'Told to deploy'
      - name: Run if false
        if:  ${{ !inputs.deploy }}
        run: |
          echo 'Told not to deploy'
