name: "DPC Static Site CI Workflow"

on:
  workflow_call:
jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Build and Test"
        run: |
          mkdir -p _site
          mkdir -p .jekyll-cache
          ./scripts/build_and_test.sh
      - name: "Check for broken links"
        uses: lycheeverse/lychee-action@v1
        with:
          fail: true
          jobSummary: true
          args: --no-progress --accept '200..=299, 401, 403, 405' .
