name: "DPC Static Site CI Workflow"

on: [push]

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Build and Test"
        run: |
          mkdir -p _site
          mkdir -p .jekyll-cache
          ./scripts/build_and_test.sh
      - name: "Check for broken links"
        uses: lycheeverse/lychee-action@82202e5e9c2f4ef1a55a3d02563e1cb6041e5332 # v2.4.1
        with:
          fail: true
          jobSummary: true
          args: --no-progress --accept '200..=299, 401, 403, 405' .
