name: 'deploy static site'

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/deploy.yml

jobs:
  deploy_static_site:
    name: Sonarqube Quality Gate
    runs-on: self-hosted
    env:
      # Workaround until https://jira.cms.gov/browse/PLT-338 is implemented.
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Add dirs"
        run: mkdir -p _site && mkdir -p .jekyll-cache
      - name: "List directory pre build"
        run: ls _site  
      - name: 'Build Image'
        run: docker build . -f Dockerfiles/Dockerfile.static_site -t static_site
      - name: 'Build Site'
        run: docker run -v ./_site:/dpc-site-static/_site -v ./.jekyll-cache:/dpc-site-static/.jekyll-cache --rm static_site
      - name: "List directory pre copy"
        run: ls _site  
      - name: 'Copy html files without suffix'
        run: find _site -name '*html' | awk '{ c=$0; gsub(".html", "", c) ; system( "cp -n " $0 " " c )}'
      - name: "List directory post build"
        run: ls _site  
      - name: Set env vars from AWS params
        uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
        env:
          AWS_REGION: us-east-1
        with:
          params: |
            SONAR_HOST_URL=/sonarqube/url
            SONAR_TOKEN=/sonarqube/token
      - name: Run quality gate scan
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args:
            -Dsonar.projectKey=bcda-dpc-static-site
            -Dsonar.sources=.
            -Dsonar.working.directory=./sonar_workspace
            -Dsonar.branch.name=${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
            -Dsonar.projectVersion=${{ github.ref_name == 'main' && github.sha || 'branch' }}
            -Dsonar.qualitygate.wait=true
      - name: "List directory pre build"
        run: ls _site  
