name: 'Test codebuilds'

on:
  push:
    paths:
      - ./.github/workflows/deploy-gf.yml
      - ./.github/workflows/broken-link-check.yml
  workflow_dispatch:

jobs:
  test_broken_links:
    uses: ./.github/workflows/broken-link-check.yml
    secrets: inherit
