name: 'Deploy Static Site'

on:
  workflow_call:
    inputs:
      target_environment:
        description: Deploy where?
        required: false
        default: 'staging'
        type: 'string'
      static_repo_ref:
        description: Which branch or tag?
        required: true
        default: 'main'
        type: 'string'
jobs:
  deploy_static_site:
    name: Deploy Static Site
    runs-on: self-hosted
    env:
      TARGET: ${{ inputs.target_environment }}
      REF: ${{ inputs.static_repo_ref }}
    steps:
      - name: Print inputs
        run: |
          echo $TARGET
          echo $REF
