name: 'Tag and Deploy Site'

on:
  push:
    paths:
      - .github/workflows/release.yml

jobs:
  tag_repo:
    name: Tag Repo
    uses: ./.github/workflows/tag_release.yml
    with:
      repo_ref: main
    secrets: inherit
  deploy:
    if: {{ env.FOO == 'bar' }}
    name: Deploy to Staging
    needs: tag_repo
    uses: ./.github/workflows/deploy.yml
    with:
      target_environment: staging
      static_repo_ref: ${{ needs.tag_repo.outputs.tag }}
    secrets: inherit
