name: 'Tag and Deploy Site'

on:
  push:
    paths:
      - .github/workflows/release.yml


jobs:
  tag_site:
    name: Tag Site
    uses: ./.github/workflows/tag_release.yml
    with:
      repo_ref: main
    secrets: inherit
  deploy:
    name: Deploy to staging
    needs: tag_site
    uses: ./.github/workflows/fake_deploy.yml
    with:
      target_environment: staging
      static_repo_ref: ${{ needs.tag_site.outputs.tag }}
