name: release

on:
  release:
    types: ['released']

jobs:
  deploy:
    permissions:
      id-token: write
    with:
      deploy_path: "uswds-redesign"
    uses: ./.github/workflows/promote.yml
    secrets: inherit
