name: 'Tag and Deploy Site (Greenfield)'

on:
  push:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Also deploy to staging?'
        type: boolean
        default: true
        required: true
      repo_ref:
        description: 'Which branch or tag?'
        required: true
        default: 'main'
        type: 'string'

jobs:
  tag_repo:
    name: Tag Repo
    runs-on: codebuild-dpc-static-site-${{github.run_id}}-${{github.run_attempt}}
    steps:
      - uses: CMSgov/dpc-app/.github/workflows/tag_release.yml@main
        with:
          repo_ref: ${{ inputs.repo_ref }}
          secrets: inherit
  deploy:
    name: Deploy to Staging
    runs-on: codebuild-dpc-static-site-${{github.run_id}}-${{github.run_attempt}}
    permissions:
      contents: read
      id-token: write
    needs: tag_repo
    steps:
      - if: ${{ inputs.deploy }}
        uses: ./.github/workflows/deploy-gf.yml
        with:
          env: staging
          static_repo_ref: ${{ needs.tag_repo.outputs.tag }}
          secrets: inherit

