name: release

on:
  release:
    types: ['released']

permissions: {}

jobs:
  deploy:
    permissions:
      id-token: write
    uses: ./.github/workflows/promote.yml
    secrets:
      PROD_ACCOUNT: ${{ secrets.PROD_ACCOUNT }}
